ZephyrCloudIO/zephyr-documentation

lib/site.config.tsx, theme/index.tsx
=> feat(chore): fix-deadlinks

components/invert-image.tsx
Our `index.md` wasn't rendering image color when switching from dark mode to light mode. This PR fix it
=> feat(chore): fix invert image issue

docs/how-to/custom-domain.mdx
Improved domains/environments section to improve user experience
=> docs: improve domains documentation

docs/recipes/react-native.mdx, lib/site.config.tsx, rspress.config.ts
Add React Native and Repack init doc
d
=> react native init

docs/general/why-zephyr-cloud.mdx
Just wanted to clean some of this page up for you guys.  I understand if you don't prefer my rewording, but I wanted to make the recommendations. I came to your site from Theo's recent video and couldn't help myself while reading up on your platform's purpose and approach.
I could go further, but I didn't want to overwhelm the …
=> Update why-zephyr-cloud.mdx for grammar and minor readability issues.

docs/recipes/vite-rspack-webpack-mf.mdx
Add known issue and ways to debug for vite federation config. 
Interrupted output bundle with `svgr()` present. 
d
=> (docs): update vite config for federation

docs/index.mdx
I noticed a grammar issue when reading the docs
@zmzlois @arthurfiorette @zackarychapple
=> Fix a grammar issue

.github/pull_request_template.md, docs/how-to/fork-our-examples.mdx, lib/site.config.tsx, rspress.config.ts
Bumped plugin version
Improved docs around forking
- Added single example cloning via degit
- maintained fork entire repo flow
Removed random "d" from this template
d - __removed this d from the template__
=> Bumped version - Improved forking docs

docs/general/create-mf-app.mdx, docs/general/why-zephyr-cloud.mdx, docs/how-to/mf-guide.mdx
Add description and example how use `zephyrDependencies` in `package.json` .
[Semver for dependency resolution](https://app.clickup.com/t/86a5njrm5)
=> feat: zephyr dependencies section

package.json, pnpm-lock.yaml, rspress.config.ts
Resolve: [CU-86a66jepw](https://app.clickup.com/t/86a66jepw)
=> [CU-86a66jepw] - Fix known 404s hitting the docs

docs/recipes/vite-rspack-webpack-mf.mdx
Additional option for vite plugin
- Provide option to allow module federation input passed in from vite config
Allowing user to use federation plugin to configure module federation 
@swalker326 @ryok90
=> feat(vite): allow both options for vite plugin

lib/site.config.tsx
I added the Svelte and the Solid examples so I'm updating the docs
Thanks :smile:
=> feat: update supported frameworks

components/zephyr/repack/start-from-scratch.mdx
Removed useless suffix bracket
n/a
n/a
=> docs: remove useless suffix bracket

.github/pull_request.yml
Adding GitHub action for dogfooding
=> feat: github pull request

docs/how-to/github-automations.mdx, rspress.config.ts
adding new docs on setting up github to build zephyr
=> feat: adding github automations doc

.github/workflows/pull_request.yml
=> fix: moving workflow to right directory

.github/workflows/pull_request.yml
=> fix: adding pnpm

docs/how-to/end-to-end-testing.mdx, package.json, pnpm-lock.yaml, rspress.config.ts
We were missing documentation on how to do e2e testing with Zephyr. This documentation adds information to our doc site on how to do it for both federated and simple applications. 
Preview can be found [here](https://t-web-latest-zackary-chapple-zephyr-cloud-docs-zephyr-0424ea-ze.zephyr-cloud.io/how-to/end-to-end-testing)
We have been asked by multiple customers for examples on how to do e2e testing with Zephyr.
No feature updates
These can be done in another task that @viktoriialurie can assign to folks to do later
No additional reviewers needed.
=> Adding E2E testing docs

docs/how-to/end-to-end-testing.mdx
Markdown title change so the sub-menu on the right side renders 
N/A
N/A
=> chore: secondary title changes

components/errors/info.tsx, docs/cloud/cloudflare.mdx, docs/cloud/netlify.mdx, docs/errors/ze20020.mdx, package.json
Add additional title and DNS details for trouble shooting Cloudflare integration. 
User added Cloudflare integration but encounter deployment error due to DNS record. 
N/A
=> feat: add DNS record to Cloudflare troubleshooting guide

.github/workflows/pull_request.yml
Add Github action deployment summary
To deploy documentation automatically on each PR
N/A
Check Github action to see if it works
=> feat: add zephyr github action

docs/recipes/rolldown-react.mdx, rspress.config.ts
Related https://github.com/ZephyrCloudIO/zephyr-packages/pull/46
This pull request includes a new guide for creating and configuring a Rolldown application with Zephyr and updates the sidebar configuration to include a link to this new guide.
Added a comprehensive guide for creating a Rolldown application and configuring it with Zephyr, including prerequisites, project creation steps, manual setup, configuration, and deployment instructions.
=> docs: rolldown plugin

docs/how-to/github-automations.mdx
Related to change in https://github.com/ZephyrCloudIO/zephyr-packages/pull/49
=> docs: update docs to include ZE_SECRET_TOKEN behaviour

docs/recipes/parcel-react.mdx, rspress.config.ts
Related to https://github.com/ZephyrCloudIO/zephyr-packages/pull/53
=> feat: add parcel docs

docs/recipes/existing-app.mdx, docs/recipes/migrate-nx-webpack-to-rspack.mdx, docs/recipes/modernjs.mdx, docs/recipes/nx-mf-app.mdx, docs/recipes/react-rspack-nx.mdx, docs/recipes/react-vite-nx.mdx, docs/recipes/turborepo-react.mdx
Fixing some typos and use rspack example where it belongs
=> docs: fix typos and use rspack plugin on proper examples

pnpm-lock.yaml
=> ci: update lockfile

components/cloud-provider.tsx, components/footer.tsx
On components/footer.tsx, div tag was chenge by footer tag to improve the semantics. The same occurre on components/cloud-provider.tsx, changing div tag by fragment tag.
=> feat: improvement html structure

.github/workflows/ci.yml, .github/workflows/on_merge.yml, components/zephyr/repack/mdx.d.ts, package.json, rspress.config.ts, scripts/build-ci.js
=> feat: temporary fix to deploy with search

components/build-auth-info.mdx, components/zephyr/repack/start-from-scratch.mdx, docs/general/create-mf-app.mdx, docs/recipes/existing-app.mdx, docs/recipes/migrate-nx-webpack-to-rspack.mdx, docs/recipes/modernjs.mdx, docs/recipes/nx-mf-app.mdx, docs/recipes/parcel-react.mdx, docs/recipes/react-rspack-nx.mdx, docs/recipes/react-vite.mdx, docs/recipes/repack-mf.mdx, docs/recipes/rolldown-react.mdx, docs/recipes/turborepo-react.mdx, lib/site.config.tsx
Auth build information to all recipes
https://github.com/ZephyrCloudIO/zephyr-packages/pull/51
https://github.com/ZephyrCloudIO/zephyr-packages/pull/51
Probably a more detailed page explaining the auth login process.
=> fix: adding auth build info to recipes

components/zephyr/repack/forked-example.mdx, components/zephyr/repack/start-from-scratch.mdx, lib/site.config.tsx, styles/index.css
Call out block for platform inference in RePack documentation
Several reported issues.
N/A
N/A
=> feat: platform inference for repack

docs/how-to/mf-guide.mdx, styles/index.css
Remove broken link and non-existing lines 
N/A
N/A 
N/A
=> feat: update docs

lib/scripts/twitter.js, rspress.config.ts
Twitter tracking script 
N/A
Twitter tracking
=> feat: twitter script

rspress.config.ts
It was fixed the double Zephyr trigger using Rspress
Enabling SSG for this to build with Zephyr was generating 2 routes: wrong one; right one; The wrong one with 404 on the assets and useless for the build.
The modification on custom plugin will be replaced by a shared Rs build plugin to support SSG for any Rs variant instead …
=> fix: add SSG to Rspress config

components/zephyr/repack/start-from-scratch.mdx
Changed react-native-repack doc
Some of the commands described in the doc were not accurate 
=> fix: changes commands and default configs

docs/general/why-zephyr-cloud.mdx, docs/index.mdx
Remove beta terminology within documentation
N/A
N/A 
@zackarychapple
=> feat: change beta stage

rspress.config.ts
=> fix: returnin zephyr usage for web thread

rspress.config.ts
=> fix: ci lint fixes

docs/general/why-zephyr-cloud.mdx
=> docs: fix typo in why-zephyr-cloud.mdx

rspress.config.ts
Fixed spelling in sidebar.
https://valerii-tropin-33-zephyr-cloud-docs-zephyr-docume-674469876-ze.zephyr-cloud.io/
@zackarychapple
=> fix: troubleshooting spelling

docs/cloud/cloudflare.mdx, docs/cloud/fastly.mdx
fixed links on cloudflare and fastly pages
https://svetlana-muravlova-valor-software-com-369-zephyr--d86f1f643-ze.zephyr-cloud.io/
=> fix(ui): fixed links on cloudflare and fstly pages

docs/cloud/fastly.mdx
here was incorrect link in api tokens
https://svetlana-muravlova-valor-software-com-261-zephyr--206ac8ae0-ze.zephyr-cloud.io/cloud/fastly
=> fix(ui): fixed link for tokens item

components/footer.tsx, theme/index.tsx
We do not have any way to trigger intercom in the docs. Now we do.
=> chore: add help button

components/footer.tsx
=> chore: discord link

lib/site.config.tsx, package.json, pnpm-lock.yaml, rspress.config.ts
=> chore: fix cards

package.json, pnpm-lock.yaml, rspress.config.ts
Move over to use rspress plugin and ssg.
=> feat: use rspress plugin
